# Generated by Django 2.1.7 on 2019-03-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('eid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('courses', models.ManyToManyField(to='tahours.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time added')),
                ('assignment', models.CharField(max_length=20)),
                ('question', models.TextField(max_length=200)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahours.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('eid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('eid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('courses', models.ManyToManyField(to='tahours.Course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahours.Student'),
        ),
        migrations.AddField(
            model_name='question',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahours.Professor'),
        ),
    ]
