# Generated by Django 2.1.7 on 2019-03-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(null=True, to='tahours.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(null=True, to='tahours.Course'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='courses',
            field=models.ManyToManyField(null=True, to='tahours.Course'),
        ),
    ]
