# Generated by Django 2.1.7 on 2019-03-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tahours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahours.Professor')),
                ('picked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked', to='tahours.TA')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted', to='tahours.TA')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tahours.Shift')),
            ],
            options={
                'ordering': ['shift'],
            },
        ),
    ]
