# Generated by Django 2.1.7 on 2019-03-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahours', '0002_auto_20190320_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(blank=True, to='tahours.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='tahours.Course'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='courses',
            field=models.ManyToManyField(blank=True, to='tahours.Course'),
        ),
    ]
