# Generated by Django 2.1.7 on 2019-03-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tahours', '0003_auto_20190320_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start', 'end']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='eid',
            new_name='student',
        ),
    ]
