# Generated by Django 2.1.7 on 2019-04-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tahours', '0003_auto_20190403_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftswap',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahours.Shift'),
        ),
    ]
