# Generated by Django 2.1.7 on 2019-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahours', '0004_auto_20190403_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tainfo',
            name='availability',
        ),
        migrations.AddField(
            model_name='tainfo',
            name='mon_avail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tainfo',
            name='sun_avail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tainfo',
            name='thur_avail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tainfo',
            name='tues_avail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tainfo',
            name='wed_avail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
