# Generated by Django 2.1.7 on 2019-03-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahours', '0004_auto_20190320_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time asked'),
        ),
    ]
